### ISSUE TITLE
Add service discovery via promregator

### ISSUE THREAD

**Issue by ScottGuymer** [philips-labs/terraform-cloudfoundry-thanos#15]
To support usage of Promregator with this module we need to support service discovery via the discovery URL in Promregator.

To enable this, we can use `file_sd` in Prometheus to update the available endpoints to be scrapped. 

`file_sd` does not support a http source and can only read from local disk. So, we need to be able to source the SD file from http location at startup and periodically update it and save it to a file within the Thanos app so it can be read.

This should be done in a generic way where you simply set the URL and it downloads the `file_sd` file from it. It is then not tied to Promregator and simply expects a Prometheus `file_sd` formatted file to live at the URL.

Probably need 2 settings, the URL and an update frequency in seconds.

This could be added as an extra supervisord process to be executed and turned on one when the URL is set. 

Once we have this we need to add the `file_sd` config to the prometheus config so that it will read the file and update the config.

**Comment by loafoe** [comment]
This would be a nice way to add external service discovery yes, nice!!

**Comment by ScottGuymer** [comment]
Started #16 to implement this

**Comment by ScottGuymer** [comment]
Tested and working! 🎉
