### ISSUE TITLE
Ability to deploy to existing space

### ISSUE THREAD

**Issue by loafoe** [philips-labs/terraform-cloudfoundry-thanos#19]
- No need for OrgAdmin permissions then
- Deploy in existing space

**Comment by ScottGuymer** [comment]
Does this infra logically belong in a different space?

The things deployed here are quite apart from the apps they are monitoring.

Do you think this module is OK having an opinion on this?

**Comment by loafoe** [comment]
I've received 3 queries this week of folks who could not use the module-as-is because they lack OrgAdmin permissions to create a separate space for deployment. 

Having the option to specify an existing space as the target provides this flexibility, so it could serve most small (single space) and large (org wide) deployments

**Comment by ScottGuymer** [comment]
I think that makes sense tbh...

It also removes some complexity from this module in creating the space, allocating permissions, preventing name clashes etc..

Should we make a breaking change and remove the space from it entirely?

**Comment by loafoe** [comment]
I was thinking more of introducing an optional `cf_space_name` variable. If present, we just skip the space creation and deploy into that space.

**Comment by loafoe** [comment]
Removed space creation completely and created a `v2.0.0` release to signal the breakage
